### PR TITLE
Move CLI logic back into distributed.cli

### PR DESCRIPTION
**Pull request by necaris**
Addresses [comments](https://github.com/dask/distributed/pull/360#discussion_r73141465) on the original PR -- simplifies the organization of the CLI logic. 

@mrocklin, is this what you meant? If so I'll continue with the other code reorganization you suggested once I understand this code better.

### CODE REVIEW

**Comment by necaris** [comment]
_Note_ to both @hussainsultan and @mrocklin -- I'm not clear what the best process is for improving someone else's PR! I'm thinking of it as a tree (submitting a transitive PR to `distributed` via @hussainsultan's fork) but would welcome your suggestions on how to operate here.

**Comment by mrocklin** [comment]
This looks like a good step to me.  

I would merge everything in the submit/ directory into a single submit.py file.  

I would have functions like `_submit` return stderr and stdout rather than write them to sys.stderr/sys.stdout and then move the writing to sys.stderr/sys.stdout to the cli code

**Comment by mrocklin** [comment]
issuing PRs to PRs sounds fine to me.  The alternative (if you wanted to sidestep @hussainsultan or get travis.ci testing immediately) would be to have your own PR to dask/master.

**Comment by hussainsultan** [comment]
@necaris thanks for the PR! i will merge it and i think it should trigger travis.

**Comment by hussainsultan** [comment]
@necaris i think your own PR here makes more sense as @mrocklin pointed out. Thanks!

**Pull request merged**
