### PR TITLE
Update S3 tests to use public S3 buckets

### PR DESCRIPTION
**Pull request by mrocklin**
I now maintain a public bucket on Continuum's account and direct all tests towards that.

### CODE REVIEW

**Comment by mrocklin** [comment]
Hrm, this is still going to fail.  We need some credentials to use boto3, even if they aren't for this account.

Is there a way to use boto3 anonymously?

**Comment by hussainsultan** [comment]
Ahh. Yes, there maybe elegant solution but in the past I have checked in a credentials file with fake AWS key and import it in test setup.

**Comment by mrocklin** [comment]
Ah, that sounds great.

**Comment by mrocklin** [comment]
I plan to give this a shot http://stackoverflow.com/questions/34865927/can-i-use-boto3-anonymously

**Comment by mrocklin** [comment]
Updated.  Tests pass for me without credentials.

**Comment by hussainsultan** [comment]
this looks awesome! Kudos for adding s3 connection caching as well. Thanks.

**Pull request merged**
